import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
    paddingBottom: 150,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 15,
    marginBottom: 24,
  },
  // listContent: {
  //   height: '100%',
  // },
  notifDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 4,
    backgroundColor: '#FF3D00',
    borderWidth: 1,
  },
  input: {
    flex: 1,
    color: '#9CA3AF',
    marginLeft: 12,
    fontSize: 16,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  searchContainerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(249, 250, 251, 0.10)',
    height: 40,
  },
  filterBtnIcon: {
    backgroundColor: '#1D1D1D',
    borderRadius: 8,
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(249, 250, 251, 0.10)',
  },
  seeAllText: {
    color: '#FFD900',
    fontSize: 14,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#FFD900',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    width: 100,
    marginHorizontal: 'auto',
  },

  filterScroll: {
    alignItems: 'center',
    height: 90,
    marginBottom: 24,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 24,
  },
  countText: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    lineHeight: 20,
  },
  sortRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortText: {
    color: '#FFD900',
    fontSize: 14,
    marginRight: 4,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    lineHeight: 20,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  locationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  locationBtnDefault: {
    backgroundColor: '#121212',
  },
  locationBtnActive: {
    backgroundColor: '#FFD900',
  },
  locationBtnText: {
    color: '#FFF',
    fontWeight: '600',
  },
  locationBtnTextActive: {
    color: '#000',
    fontWeight: '600',
  },
  resetBtn: {
    padding: 6,
    borderRadius: 24,
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  dropdown: {
    position: 'absolute',
    top: 44,
    left: 0,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    minWidth: 180,
    zIndex: 20,
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  dropdownItemText: {
    fontSize: 15,
    color: '#FFF',
  },
  dropdownItemTextActive: {
    fontSize: 15,
    color: '#FFD900',
  },
});
