# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# $RNFirebaseAsStaticFramework = true

# platform :ios, '15.1'
# prepare_react_native_project!

# target 'filip' do
#   $RNFirebaseAsStaticFramework = true
#   # use_frameworks! :linkage => :static

#   pod 'GoogleUtilities', :modular_headers => true
#   pod 'FirebaseCoreInternal', :modular_headers => true
#   pod 'RecaptchaInterop', :modular_headers => true
#   pod 'FirebaseAppCheckInterop', :modular_headers => true
#   pod 'FirebaseAuthInterop', :modular_headers => true
#   pod 'FirebaseMessagingInterop', :modular_headers => true
#   pod 'FirebaseFirestoreInternal', :modular_headers => true
#   pod 'FirebaseAuth', :modular_headers => true
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseCoreExtension', :modular_headers => true
#   pod 'FirebaseSharedSwift', :modular_headers => true
#   pod 'GTMSessionFetcher', :modular_headers => true
#   pod 'FirebaseStorage', :modular_headers => true
#   pod 'FirebaseMessaging', :modular_headers => true
#   pod 'FirebaseFunctions', :modular_headers => true
#   pod 'FirebaseFirestore', :modular_headers => true
#   pod 'Firebase', :modular_headers => true

#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#     )
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |build_config|
#         build_config.build_settings['RCT_NEW_ARCH_ENABLED'] = '0'
#         build_config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
#         build_config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
#         build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
#         build_config.build_settings['WARNING_CFLAGS'] = '-w'
#         build_config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
#         build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#         build_config.build_settings['OTHER_CFLAGS'] = '$(inherited) -w -Wno-error'
#         build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -w -Wno-error'
#       end
#     end
#   end
# end

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

$RNFirebaseAsStaticFramework = true

platform :ios, '15.1'
prepare_react_native_project!

target 'filip' do
  $RNFirebaseAsStaticFramework = true
  use_frameworks! :linkage => :static

  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseSharedSwift', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'FirebaseFunctions', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'Firebase', :modular_headers => true

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        build_config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        build_config.build_settings['WARNING_CFLAGS'] = '-w'
        build_config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        build_config.build_settings['OTHER_CFLAGS'] = '$(inherited) -w -Wno-error'
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -w -Wno-error'
      end
    end
  end
end